In [1]:
import pandas as pd
import numpy as np

# Slice de arrary

In [2]:
ar=np.array([1,2,3,4,5,6,7])

In [3]:
ar[3]

4

In [4]:
ar[0:3]

array([1, 2, 3])

In [5]:
ar[0:-4]

array([1, 2, 3])

In [6]:
ar[0:-4]

array([1, 2, 3])

In [7]:
ar[-4:0]

array([], dtype=int32)

In [8]:
ar[:-2]

array([1, 2, 3, 4, 5])

In [9]:
ar[0:3]

array([1, 2, 3])

# Matrices de varias dimenciones

In [10]:
matrix3D = np.array([[[1, 2],[3, 4]], [[5, 6],[7, 8]], [[4,8],[5,6]]])
matrix3D[0,0,:]

array([1, 2])

# Tipos de datos

In [11]:
arr1=np.array([1,2,3,4])
arr1.dtype

dtype('int32')

In [12]:
arr=np.array([1,2,3,4],dtype='float')
arr.dtype

dtype('float64')

In [13]:
arr2=arr1.astype(np.float64)
arr2

array([1., 2., 3., 4.])

In [14]:
arr2=arr1.astype(np.bool_)
arr2

array([ True,  True,  True,  True])

In [15]:
arr2=arr1.astype(np.str_)
arr2

array(['1', '2', '3', '4'], dtype='<U11')

# Dimensiones

In [16]:
scalar = np.array(1)
scalar
scalar.ndim

0

In [17]:
vector=np.array([1,2,3])
vector
vector.ndim

1

In [18]:
matrix=np.array([[1,2],[3,4],[5,6]])
matrix
matrix.ndim

2

In [19]:
tensor=np.array([[[1,2],[3,4],[5,6]] , [[1,8],[3,6],[5,6]] ])
tensor
tensor.ndim


3

In [20]:
#Añadimos dimensiones
matrix2=np.expand_dims(matrix,axis=0)
matrix2
matrix2.ndim

3

In [21]:
#eliminamos dimensiones que no se usan
matrix3=np.squeeze(matrix)
matrix3.ndim

2

In [22]:
## Crear arrays

In [23]:
ar1=np.array(range(0,10))
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
ar2=np.array(range(0,10,2))
ar2

array([0, 2, 4, 6, 8])

In [25]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [27]:
np.linspace(0,10,16)

array([ 0.        ,  0.66666667,  1.33333333,  2.        ,  2.66666667,
        3.33333333,  4.        ,  4.66666667,  5.33333333,  6.        ,
        6.66666667,  7.33333333,  8.        ,  8.66666667,  9.33333333,
       10.        ])

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.random.rand(2,4,3)

array([[[0.8240448 , 0.07040413, 0.84717829],
        [0.741019  , 0.04172413, 0.58730293],
        [0.11930405, 0.46432212, 0.76578361],
        [0.87550235, 0.6142227 , 0.85382619]],

       [[0.16317563, 0.3367433 , 0.01439571],
        [0.74017718, 0.59422266, 0.45589876],
        [0.00410881, 0.33538916, 0.8392969 ],
        [0.39715057, 0.726873  , 0.8240054 ]]])

In [30]:
np.random.randint(1,100,(2,2,2))

array([[[ 5, 78],
        [34, 11]],

       [[ 4,  7],
        [11, 61]]])

In [31]:
np.random.randint(1,100,(2,2,4))

array([[[78, 80, 78, 65],
        [86, 98, 15,  6]],

       [[48, 20, 44, 85],
        [71, 15, 43, 47]]])

# Funciones principales

In [32]:
arr6=np.random.randint(10,30,20)
arr6

array([17, 13, 20, 16, 15, 11, 24, 16, 16, 13, 16, 29, 25, 18, 25, 22, 29,
       18, 15, 12])

In [33]:
np.percentile(arr6,50)

16.5

In [34]:
np.median(arr6)

16.5

In [35]:
np.std(arr6)

5.296225070746145

In [36]:
np.var(arr6)

28.05

In [37]:
np.mean(arr6)

18.5

In [38]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concatenate((a,b), axis=1)
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [39]:
c.T

array([[1, 3],
       [2, 4],
       [5, 7],
       [6, 8]])

# Operaciones

In [40]:
arr7=np.arange(0,10)
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr7*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
matriz6=arr7.reshape(2,5)
matriz6

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
matriz7=matriz6*2

In [44]:
matriz8=matriz7.T.copy()
matriz8

array([[ 0, 10],
       [ 2, 12],
       [ 4, 14],
       [ 6, 16],
       [ 8, 18]])

In [45]:
#Multiplicacion de matrices
np.matmul(matriz7,matriz8)

array([[ 120,  320],
       [ 320, 1020]])

# series y data frames

In [46]:
psg_player=pd.Series(['Navas','mbappe','messi'],index=[1,3,5])


In [47]:
poll={1:'lol',2:'lilll'}
poll


{1: 'lol', 2: 'lilll'}

# Leer archivos, loc e iloc

In [48]:
df=pd.read_csv(f'books_info.csv',sep=",")
df

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [49]:
df.loc[0:4,['Name','Author']]

Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [50]:
df.iloc[0:4,0:2]

Name              Author
0            10-Day Green Smoothie Cleanse            JJ Smith
1                        11/22/63: A Novel        Stephen King
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson
3                   1984 (Signet Classics)       George Orwell

In [51]:
df.iloc[0:4,[0,1]]

Name              Author
0            10-Day Green Smoothie Cleanse            JJ Smith
1                        11/22/63: A Novel        Stephen King
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson
3                   1984 (Signet Classics)       George Orwell

In [52]:
df.iloc[0:4,[0,4,6,1]]

Name  Price        Genre  \
0            10-Day Green Smoothie Cleanse      8  Non Fiction   
1                        11/22/63: A Novel     22      Fiction   
2  12 Rules for Life: An Antidote to Chaos     15  Non Fiction   
3                   1984 (Signet Classics)      6      Fiction   

               Author  
0            JJ Smith  
1        Stephen King  
2  Jordan B. Peterson  
3       George Orwell

# Agregar o quitar datos de pandas

In [53]:
#Solo lo borra de la salida
df.drop('Year',axis=1).head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

         Genre  
0  Non Fiction  
1      Fiction

In [54]:
df.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [55]:
df.drop('Year',axis=1,inplace=True)

In [56]:
df.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

         Genre  
0  Non Fiction  
1      Fiction

In [60]:
df.drop([0,1,3],axis=0).head(2)



Name  \
2            12 Rules for Life: An Antidote to Chaos   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price        Genre  
2        Jordan B. Peterson          4.7    18979     15  Non Fiction  
4  National Geographic Kids          4.8     7665     12  Non Fiction

In [63]:
df.drop(range(0,10),axis=0).head(2)

Name            Author  \
10                          A Man Called Ove: A Novel   Fredrik Backman   
11  A Patriot's History of the United States: From...  Larry Schweikart   

    User Rating  Reviews  Price        Genre  
10          4.6    23848      8      Fiction  
11          4.6      460      2  Non Fiction

In [65]:
df['nueva_columna']=np.nan
df.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

         Genre  nueva_columna  
0  Non Fiction            NaN  
1      Fiction            NaN

In [71]:
pp={'col1':[1,2,3,np.nan],'col2':[4,np.nan,6,7],'col3':['a','b','c',None]}
df2=pd.DataFrame(pp)
df2

col1  col2  col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

In [72]:
df2.isnull()

col1   col2   col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [73]:
df2.isnull()*1

col1  col2  col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [75]:
df2.fillna('Missing')

col1     col2     col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [82]:
df2['col1']=df2['col1'].fillna(df2['col1'].mean())
df2

col1  col2  col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   2.0   7.0  None

In [83]:
df2['col2']=df2['col2'].interpolate()
df2


col1  col2  col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   2.0   7.0  None

In [ ]:
df2['col2']=df2['col2'].interpolate()
df2


col1  col2  col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   2.0   7.0  None

In [84]:
df2.dropna()

col1  col2 col3
0   1.0   4.0    a
1   2.0   5.0    b
2   3.0   6.0    c