In [47]:
import pandas as pd
import numpy as np

# Slice de arrary

In [78]:
ar=np.array([1,2,3,4,5,6,7])

In [79]:
ar[3]

4

In [80]:
ar[0:3]

array([1, 2, 3])

In [81]:
ar[0:-4]

array([1, 2, 3])

In [82]:
ar[0:-4]

array([1, 2, 3])

In [83]:
ar[-4:0]

array([], dtype=int32)

In [84]:
ar[:-2]

array([1, 2, 3, 4, 5])

In [85]:
ar[0:3]

array([1, 2, 3])

# Matrices de varias dimenciones

In [86]:
matrix3D = np.array([[[1, 2],[3, 4]], [[5, 6],[7, 8]], [[4,8],[5,6]]])
matrix3D[0,0,:]

array([1, 2])

# Tipos de datos

In [87]:
arr1=np.array([1,2,3,4])
arr1.dtype

dtype('int32')

In [88]:
arr=np.array([1,2,3,4],dtype='float')
arr.dtype

dtype('float64')

In [89]:
arr2=arr1.astype(np.float64)
arr2

array([1., 2., 3., 4.])

In [90]:
arr2=arr1.astype(np.bool_)
arr2

array([ True,  True,  True,  True])

In [91]:
arr2=arr1.astype(np.str_)
arr2

array(['1', '2', '3', '4'], dtype='<U11')

# Dimensiones

In [97]:
scalar = np.array(1)
scalar
scalar.ndim

0

In [98]:
vector=np.array([1,2,3])
vector
vector.ndim

1

In [99]:
matrix=np.array([[1,2],[3,4],[5,6]])
matrix
matrix.ndim

2

In [103]:
tensor=np.array([[[1,2],[3,4],[5,6]] , [[1,8],[3,6],[5,6]] ])
tensor
tensor.ndim


3

In [106]:
#Añadimos dimensiones
matrix2=np.expand_dims(matrix,axis=0)
matrix2
matrix2.ndim

3

In [107]:
#eliminamos dimensiones que no se usan
matrix3=np.squeeze(matrix)
matrix3.ndim

2

In [ ]:
## Crear arrays

In [112]:
ar1=np.array(range(0,10))
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
ar2=np.array(range(0,10,2))
ar2

array([0, 2, 4, 6, 8])

In [122]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [123]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [126]:
np.linspace(0,10,16)

array([ 0.        ,  0.66666667,  1.33333333,  2.        ,  2.66666667,
        3.33333333,  4.        ,  4.66666667,  5.33333333,  6.        ,
        6.66666667,  7.33333333,  8.        ,  8.66666667,  9.33333333,
       10.        ])

In [127]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [132]:
np.random.rand(2,4,3)

array([[[0.54624763, 0.97690227, 0.17614642],
        [0.17995393, 0.32796325, 0.72395288],
        [0.43759634, 0.73463674, 0.76034997],
        [0.05414419, 0.26510695, 0.88144496]],

       [[0.50135921, 0.42446557, 0.19991727],
        [0.77223857, 0.68448136, 0.73398472],
        [0.39486712, 0.23877005, 0.60078252],
        [0.0647091 , 0.54506414, 0.43543429]]])

In [135]:
np.random.randint(1,100,(2,2,2))

array([[[35, 69],
        [ 9, 34]],

       [[71, 50],
        [64, 94]]])

In [1]:
np.random.randint(1,100,(2,2,4))

NameError: name 'np' is not defined

# Funciones principales

In [8]:
arr6=np.random.randint(10,30,20)
arr6

array([22, 18, 14, 22, 15, 29, 16, 28, 23, 11, 12, 16, 21, 12, 12, 19, 28,
       18, 27, 21])

In [9]:
np.percentile(arr6,50)

18.5

In [12]:
np.median(arr6)

18.5

In [13]:
np.std(arr6)

5.653317610041029

In [14]:
np.var(arr6)

31.960000000000008

In [15]:
np.mean(arr6)

19.2

In [25]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concatenate((a,b), axis=1)
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [26]:
c.T

array([[1, 3],
       [2, 4],
       [5, 7],
       [6, 8]])

# Operaciones

In [29]:
arr7=np.arange(0,10)
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr7*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
matriz6=arr7.reshape(2,5)
matriz6

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
matriz7=matriz6*2

In [37]:
matriz8=matriz7.T.copy()
matriz8

array([[ 0, 10],
       [ 2, 12],
       [ 4, 14],
       [ 6, 16],
       [ 8, 18]])

In [39]:
#Multiplicacion de matrices
np.matmul(matriz7,matriz8)

array([[ 120,  320],
       [ 320, 1020]])

# series y data frames

In [43]:
psg_player=pd.Series(['Navas','mbappe','messi'],index=[1,3,5])


In [45]:
poll={1:'lol',2:'lilll'}
poll


{1: 'lol', 2: 'lilll'}

# Leer archivos, loc e iloc

In [82]:
df=pd.read_csv(f'books_info.csv',sep=",")
df

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [71]:
df.loc[0:4,['Name','Author']]

Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [90]:
df.iloc[0:4,0:2]

Name              Author
0            10-Day Green Smoothie Cleanse            JJ Smith
1                        11/22/63: A Novel        Stephen King
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson
3                   1984 (Signet Classics)       George Orwell

In [95]:
df.iloc[0:4,[0,1]]

Name              Author
0            10-Day Green Smoothie Cleanse            JJ Smith
1                        11/22/63: A Novel        Stephen King
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson
3                   1984 (Signet Classics)       George Orwell

In [97]:
df.iloc[0:4,[0,4,6,1]]

Name  Price        Genre  \
0            10-Day Green Smoothie Cleanse      8  Non Fiction   
1                        11/22/63: A Novel     22      Fiction   
2  12 Rules for Life: An Antidote to Chaos     15  Non Fiction   
3                   1984 (Signet Classics)      6      Fiction   

               Author  
0            JJ Smith  
1        Stephen King  
2  Jordan B. Peterson  
3       George Orwell

# Agregar o quitar datos de pandas

In [101]:
#Solo lo borra de la salida
df.drop('Year',axis=1).head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

         Genre  
0  Non Fiction  
1      Fiction

In [102]:
df.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [103]:
df.drop('Year',axis=1,inplace=True)

In [105]:
df.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

         Genre  
0  Non Fiction  
1      Fiction