In [77]:
import pandas as pd
import numpy as np

# Slice de arrary

In [78]:
ar=np.array([1,2,3,4,5,6,7])

In [79]:
ar[3]

4

In [80]:
ar[0:3]

array([1, 2, 3])

In [81]:
ar[0:-4]

array([1, 2, 3])

In [82]:
ar[0:-4]

array([1, 2, 3])

In [83]:
ar[-4:0]

array([], dtype=int32)

In [84]:
ar[:-2]

array([1, 2, 3, 4, 5])

In [85]:
ar[0:3]

array([1, 2, 3])

# Matrices de varias dimenciones

In [86]:
matrix3D = np.array([[[1, 2],[3, 4]], [[5, 6],[7, 8]], [[4,8],[5,6]]])
matrix3D[0,0,:]

array([1, 2])

# Tipos de datos

In [87]:
arr1=np.array([1,2,3,4])
arr1.dtype

dtype('int32')

In [88]:
arr=np.array([1,2,3,4],dtype='float')
arr.dtype

dtype('float64')

In [89]:
arr2=arr1.astype(np.float64)
arr2

array([1., 2., 3., 4.])

In [90]:
arr2=arr1.astype(np.bool_)
arr2

array([ True,  True,  True,  True])

In [91]:
arr2=arr1.astype(np.str_)
arr2

array(['1', '2', '3', '4'], dtype='<U11')

# Dimensiones

In [97]:
scalar = np.array(1)
scalar
scalar.ndim

0

In [98]:
vector=np.array([1,2,3])
vector
vector.ndim

1

In [99]:
matrix=np.array([[1,2],[3,4],[5,6]])
matrix
matrix.ndim

2

In [103]:
tensor=np.array([[[1,2],[3,4],[5,6]] , [[1,8],[3,6],[5,6]] ])
tensor
tensor.ndim


3

In [106]:
#Añadimos dimensiones
matrix2=np.expand_dims(matrix,axis=0)
matrix2
matrix2.ndim

3

In [107]:
#eliminamos dimensiones que no se usan
matrix3=np.squeeze(matrix)
matrix3.ndim

2

In [ ]:
## Crear arrays

In [112]:
ar1=np.array(range(0,10))
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
ar2=np.array(range(0,10,2))
ar2

array([0, 2, 4, 6, 8])

In [122]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [123]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [126]:
np.linspace(0,10,16)

array([ 0.        ,  0.66666667,  1.33333333,  2.        ,  2.66666667,
        3.33333333,  4.        ,  4.66666667,  5.33333333,  6.        ,
        6.66666667,  7.33333333,  8.        ,  8.66666667,  9.33333333,
       10.        ])

In [127]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [132]:
np.random.rand(2,4,3)

array([[[0.54624763, 0.97690227, 0.17614642],
        [0.17995393, 0.32796325, 0.72395288],
        [0.43759634, 0.73463674, 0.76034997],
        [0.05414419, 0.26510695, 0.88144496]],

       [[0.50135921, 0.42446557, 0.19991727],
        [0.77223857, 0.68448136, 0.73398472],
        [0.39486712, 0.23877005, 0.60078252],
        [0.0647091 , 0.54506414, 0.43543429]]])

In [135]:
np.random.randint(1,100,(2,2,2))

array([[[35, 69],
        [ 9, 34]],

       [[71, 50],
        [64, 94]]])